repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: debug-statements
      - id: check-ast
      - id: detect-private-key
      - id: check-json
      - id: check-case-conflict
      - id: check-builtin-literals
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.284
    hooks:
    - id: pyright
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: "v0.32.0" # Use the sha / tag you want to point at
    hooks:
      - id: yapf

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-isort==5.0.3,
            flake8-blind-except==0.2.1,
            flake8-broken-line==0.6.0,
            flake8-bugbear==22.10.27,
            flake8-builtins==2.0.1,
            flake8-class-attributes-order==0.1.3,
            flake8-cognitive-complexity==0.1.0,
            flake8-commas==2.1.0,
            flake8-comprehensions==3.10.1,
            flake8-debugger==4.1.2,
            flake8-eradicate==1.4.0,
            flake8-functions==0.0.7,
            flake8-isort==5.0.3,
            flake8-mutable==1.2.0,
            flake8-print==5.0.0,
            flake8-pytest==1.4,
            flake8-pytest-style==1.6.0,
            flake8-quotes==3.3.1,
            flake8-string-format==0.3.0,
            flake8-variables-names==0.0.5,
            flake8-isort==5.0.3,
          ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest run
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
      - id: isort
        name: isort
        entry: isort
        language: python

default_language_version:
  python: python3
