version: "3.9"

services:
  postgres:
    container_name: pg_cnt
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - innerNetwork
    env_file:
      - .env
  webapp:
    container_name: link_cutter_cnt
    image: link_cutter
    build:
      context: .
    env_file:
      - .env
    command: ./utils/wait-for.sh postgres:5432 -- python3 src/main.py
    environment:
      POSTGRES_HOST: 'postgres'
    ports:
      - "8080:8080"
    networks:
      - innerNetwork
  pgadmin:
    container_name: pgadmin_cnt
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8088:80"
    networks:
      - innerNetwork
    depends_on:
      - postgres
networks:
  innerNetwork:
    driver: bridge
volumes:
  pgdata:
