logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    stdformat:
      format: "{asctime} {levelname} {name}  {message}"
      style: "{"
  handlers:
    console:
      class: logging.StreamHandler
      level: "DEBUG"
      formatter: stdformat
      stream: "ext://sys.stdout"
  root:
    level: "DEBUG"
    handlers: ["console"]
